export const CAPABILITIES = Object.freeze([
  {
    id: 'travel.search',
    label: 'Search transport',
    action: 'read',
    keywords: ['travel', 'transport', 'train', 'rail', 'route', 'journey', 'passage', 'fare', 'ticket', 'departure', 'arrival', 'service'],
    phrases: ['find routes', 'search journeys', 'available trains', 'transport options'],
    schemaCues: ['from', 'origin', 'leaving', 'departure', 'to', 'destination', 'arriving', 'arrival', 'date', 'day', 'passengers', 'travellers'],
    requiredConcepts: ['origin', 'destination', 'date'],
  },
  {
    id: 'travel.hold',
    label: 'Hold transport option',
    action: 'reversible',
    keywords: ['travel', 'transport', 'train', 'rail', 'fare', 'ticket', 'quote', 'hold', 'freeze', 'lock', 'reserve'],
    phrases: ['hold fare', 'reserve ticket', 'freeze quote', 'temporary reservation'],
    schemaCues: ['quote', 'quoteid', 'journey', 'journeyid', 'ticket', 'option', 'expires'],
    requiredConcepts: ['travelOptionId'],
  },
  {
    id: 'accommodation.search',
    label: 'Search accommodation',
    action: 'read',
    keywords: ['accommodation', 'hotel', 'room', 'stay', 'property', 'lodging', 'night', 'shelter', 'space', 'bed'],
    phrases: ['find rooms', 'search hotels', 'available stays', 'places to sleep'],
    schemaCues: ['near', 'location', 'destination', 'checkin', 'checkout', 'nights', 'guests', 'nightly', 'budget'],
    requiredConcepts: ['location', 'date'],
  },
  {
    id: 'accommodation.hold',
    label: 'Hold accommodation',
    action: 'reversible',
    keywords: ['accommodation', 'hotel', 'room', 'stay', 'property', 'lodging', 'night', 'space', 'hold', 'reserve', 'lock'],
    phrases: ['hold room', 'reserve stay', 'temporary booking', 'lock accommodation'],
    schemaCues: ['room', 'roomid', 'space', 'spacecode', 'property', 'propertyid', 'checkin', 'nights'],
    requiredConcepts: ['accommodationOptionId'],
  },
  {
    id: 'location.distance',
    label: 'Measure access distance',
    action: 'read',
    keywords: ['distance', 'walk', 'walking', 'map', 'location', 'geo', 'route', 'access', 'nearby', 'minutes', 'kilometres', 'miles'],
    phrases: ['walking distance', 'measure route', 'distance matrix', 'travel time'],
    schemaCues: ['origin', 'origins', 'candidate', 'candidates', 'destination', 'mode', 'address', 'addresses'],
    requiredConcepts: ['candidates', 'destination'],
  },
]);

export const CAPABILITY_BY_ID = new Map(CAPABILITIES.map((item) => [item.id, item]));

export const INPUT_ALIASES = Object.freeze({
  origin: ['origin', 'from', 'start', 'leaving', 'departure', 'departing', 'source'],
  destination: ['destination', 'to', 'end', 'arriving', 'arrival', 'target', 'near'],
  date: ['date', 'day', 'traveldate', 'departdate', 'checkin', 'check_in'],
  passengers: ['passengers', 'travellers', 'travelers', 'people', 'party'],
  location: ['location', 'near', 'destination', 'area', 'place', 'city'],
  nights: ['nights', 'duration', 'nightcount', 'staylength'],
  guests: ['guests', 'people', 'party', 'travellers', 'travelers'],
  maxPrice: ['maxprice', 'max_price', 'budget', 'limit', 'nightlylimit', 'maxnightlyprice'],
  travelOptionId: ['quoteid', 'quote_id', 'quoteref', 'quote_ref', 'journeyid', 'journey_id', 'ticketid', 'optionid', 'fareid', 'reference'],
  accommodationOptionId: ['spacecode', 'space_code', 'roomid', 'room_id', 'propertyid', 'optionid', 'stayid', 'reference'],
  candidates: ['candidates', 'origins', 'addresses', 'places', 'properties', 'items'],
  mode: ['mode', 'travelmode', 'method'],
});

export const OUTPUT_ALIASES = Object.freeze({
  arrays: ['options', 'results', 'journeys', 'routes', 'services', 'spaces', 'rooms', 'properties', 'stays', 'measures', 'distances', 'items'],
  id: ['id', 'quoteid', 'quote_id', 'quoteref', 'quote_ref', 'journeyid', 'journey_id', 'optionid', 'option_id', 'spacecode', 'space_code', 'roomid', 'room_id', 'propertyid', 'reference'],
  provider: ['provider', 'operator', 'brand', 'company', 'name'],
  label: ['label', 'name', 'title', 'hotel', 'property'],
  origin: ['origin', 'from', 'leaving', 'departurestation'],
  destination: ['destination', 'to', 'arriving', 'arrivalstation'],
  departAt: ['departat', 'depart_at', 'departure', 'departuretime', 'leaves'],
  arriveAt: ['arriveat', 'arrive_at', 'arrival', 'arrivaltime'],
  price: ['price', 'fare', 'cost', 'amount', 'nightly', 'nightlyprice', 'total'],
  address: ['address', 'location', 'street', 'vicinity'],
  walkingMinutes: ['walkingminutes', 'walking_minutes', 'minutes', 'walktime', 'durationminutes'],
  distanceKm: ['distancekm', 'distance_km', 'kilometres', 'kilometers', 'km'],
  holdId: ['holdid', 'hold_id', 'reservationid', 'reservation_id', 'reference'],
  expiresAt: ['expiresat', 'expires_at', 'expiry', 'expires'],
});
