import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.resolve(process.argv[2] ?? path.join(root,'release'));
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
for(const item of ['index.html','styles.css','manifest.webmanifest','vercel.json','robots.txt','llms.txt','.nojekyll','LICENSE','README.md','package.json','js','providers','assets','docs','scripts','tests','.github']) await cp(path.join(root,item),path.join(out,item),{recursive:true});
const commit=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).stdout.trim();
await writeFile(path.join(out,'BUILD-INFO.json'),JSON.stringify({commit,builtAt:new Date().toISOString(),tests:'npm run validate:ci',e2e:'npm run e2e:standalone'},null,2)+'\n');
console.log(`Release tree written to ${out}`);
